CREATE DATABSE CONTACTOS;

USE CONTACTOS;

CREATE TABLE USUARIOS(
 ID INT NOT NULL PRIMARY KEY,
 NOMBRE VARCHAR(20),
 EMAIL VARCHAR(50),
 PASSWORD VARCHAR(50),
 IMG VARCHAR(10),
);

CREATE TABLE CONTACTO(
 ID INT NOT NULL PRIMARY KEY,
 IMG VARCHAR(10),
 NOMBRE varchar(20),
 INFORMACION VARCHAR(100)
);